mtd: add missing prototype for mtd_read_oob_bf()
This patch fixes the following build error:

cmd/nand.c: In function 'nand_watch_bf':
cmd/nand.c:248:23: error: implicit declaration of function 'mtd_read_oob_bf'; did you mean 'mtd_read_oob'? [-Wimplicit-function-declaration]
  248 |                 ret = mtd_read_oob_bf(mtd, addr, &ops);
      |                       ^~~~~~~~~~~~~~~
      |                       mtd_read_oob

Fixes: 1fac57720719 ("nand: Add a watch command")
Signed-off-by: Shiji Yang <yangshiji66@outlook.com>